apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    kubernetes.io/name: "ciproxy"
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        release: {{ .Release.Name | quote }}
    spec:
      containers:
      - name: "{{ .Values.name }}"
        env:
        # - name: GITLAB_API
        #   value: {{ .Values.api }}
        # - name: GITLAB_TOKEN
        #   value: {{ .Values.token }}
        - name: GLOBAL_CONFIG_YML
          value: {{ .Values.yaml }}
        - name: DB_USERNAME
          value: {{ .Values.db.user }}
        - name: DB_PASSWORD
          value: {{ .Values.db.password }}
        - name: DB_NAME
          value: {{ .Values.db.name }}
        - name: DB_HOST
          value: {{ .Values.db.host }}
        - name: DB_POOL_SIZE
          value: "{{ .Values.db.pool }}"
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 4001
          name: ciproxy
        livenessProbe:
          httpGet:
            path: /
            port: 4001
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 10
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
