apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: {{ .Values.name }}
  namespace: default
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - ciproxy:
              serviceName: {{ .Values.name }}
              servicePort: {{ .Values.ingress.port }}
            path: /v1/ciproxy


