apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    kubernetes.io/name: "ciproxy"
    app: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
  - name: ciproxy
    port: 4001
  type: {{ .Values.serviceType }}
